spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root123
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
