spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    # publisher-confirms默认为false
    publisher-confirms: true
    # publisher-returns默认为false
    publisher-returns: true
    listener:
      # 默认为sample
      type: direct
      direct:
        # 默认为AUTO
        acknowledge-mode: AUTO
      simple:
        # 默认为AUTO
        acknowledge-mode: MANUAL

logging:
  level.*: INFO