spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    # publisher-confirms默认为false
    publisher-confirms: false
    # publisher-returns默认为false
    publisher-returns: false
    listener:
      # 默认为sample
      type: direct
      direct:
        # 默认为AUTO
        acknowledge-mode: MANUAL
      simple:
        # 默认为AUTO
        acknowledge-mode: MANUAL

logging:
  level.*: INFO